services:
  db:
    image: "mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senha@1234

  phpmyadmin:  
    image: "phpmyadmin/phpmyadmin"
    ports: 
      - 8080:80
